---
- name: Create a new Demo EC2 instance
  hosts: local
  connection: local
  gather_facts: False

  vars:
      region: ap-south-1
      instance_type: t2.micro
      ami: ami-f4cc1de2  # Ubuntu 16.04 LTS
      keypair: redhat # pem file name
  
  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         group: sg-004e0e3350abf0164  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: test
         instance_tags:
            Name: pcfunda
         vpc_subnet_id: subnet-19e0cc71
         assign_public_ip: yes
      register: ec2